// Generated by CoffeeScript 1.6.2
(function() {
  var configTarget, getMock, mockery, must, sinon, _clearSarcasm, _createSarcasm, _mock, _target, _verifySarcasm;

  sinon = require('sinon');

  mockery = require('mockery');

  mockery.enable({
    warnOnReplace: false,
    warnOnUnregistered: false
  });

  _mock = {};

  _target = null;

  _createSarcasm = function() {
    _mock = sinon.mock(_target);
    return _mock;
  };

  _clearSarcasm = function() {
    return _mock.restore();
  };

  _verifySarcasm = function() {
    return _mock.verify();
  };

  configTarget = function(dependencyName, target) {
    mockery.registerMock(dependencyName, target);
    return _target = target;
  };

  getMock = function() {
    return _mock;
  };

  must = function(name, configCallback) {
    return it(name, function(done) {
      _createSarcasm();
      configCallback();
      _verifySarcasm();
      _clearSarcasm();
      return done();
    });
  };

  module.exports = {
    must: must,
    configTarget: configTarget,
    getMock: getMock
  };

}).call(this);
