// Generated by CoffeeScript 1.6.2
(function() {
  var AppCatalogEntry, findAll, findById, put, service;

  AppCatalogEntry = require('./appCatalogEntry');

  findAll = function(callback) {
    return AppCatalogEntry.find({}, '', function(err, result) {
      return callback(err, result);
    });
  };

  findById = function(id, callback) {
    return AppCatalogEntry.findOne({
      'id': id
    }, '', callback);
  };

  put = function(body, callback) {
    var ex;

    try {
      return AppCatalogEntry.validate(body, function(errs) {
        var entry;

        if (errs != null) {
          return callback(errs);
        } else {
          entry = new AppCatalogEntry(body);
          return AppCatalogEntry.update({
            'id': body.id
          }, {
            $set: body,
            $inc: {
              docVersion: 1
            }
          }, {
            upsert: true
          }, function(err, data) {
            return callback(err);
          });
        }
      });
    } catch (_error) {
      ex = _error;
      return callback(ex);
    }
  };

  service = {
    Model: AppCatalogEntry,
    findAll: findAll,
    findById: findById,
    put: put
  };

  module.exports = service;

}).call(this);
