// Generated by CoffeeScript 1.6.2
(function() {
  var app, args, server, settings, settingsModule;

  args = process.argv.splice(2);

  settingsModule = args[0] || './settings';

  settings = require(settingsModule);

  server = require('./serverClass');

  app = server(settings);

}).call(this);
