// Generated by CoffeeScript 1.6.2
(function() {
  var config;

  config = {};

  config.entryRoute = '/entry';

  config.localPort = 8081;

  if (process.env.PORT == null) {
    config.mongoUrl = 'mongodb://appcatalog:appcatalog101#@ds061237.mongolab.com:61237/appcatalogprod';
  } else {
    config.mongoUrl = 'mongodb://appcatalog:appcatalog101#@ds061237.mongolab.com:61237/appcatalogprod';
  }

  module.exports = config;

}).call(this);
