// Generated by CoffeeScript 1.6.2
(function() {
  var app, put, request, server, settings, should, testData;

  request = require('supertest');

  server = require('./serverClass');

  settings = require('./settingslocal');

  should = require('should');

  testData = require('./testData');

  app = server(settings);

  put = function(entry, expectStatus, assertCallback) {
    return request(app).put('/entry').type('application/json').send(entry).expect('Content-Type', /json/).end(assertCallback);
  };

  describe('PUT /entry for Happy Path With Required Data', function() {
    return it('responds with JSON success message', function(done) {
      var entry;

      entry = testData.fullyValidEntry();
      return put(entry, 200, function(err, res) {
        var message;

        should.not.exist(err);
        message = JSON.parse(res.text);
        should.exist(message);
        message.status.should.eql(200);
        message.message.should.eql('Successfully updated entry');
        return done();
      });
    });
  });

  describe('PUT /entry for Failure Path With Invalid JSON', function() {
    return it('responds with JSON failure message', function(done) {
      var entry;

      entry = {
        "idNotAValidName": "FailurePathWithInvalidJSON"
      };
      return put(entry, 500, function(err, res) {
        var message;

        should.not.exist(err);
        message = JSON.parse(res.text);
        should.exist(message);
        message.status.should.eql(500);
        message.message.title.should.eql('Could not process your request due to validation errors');
        return done();
      });
    });
  });

}).call(this);
