// Generated by CoffeeScript 1.6.2
(function() {
  var app, fs, put, request, server, settings, should, testData;

  fs = require('fs');

  request = require('supertest');

  server = require('./serverClass');

  settings = require('./settingslocal');

  should = require('should');

  testData = require('./testData');

  app = server(settings);

  put = function(entry, expectStatus, assertCallback) {
    return request(app).put('/entry').type('application/json').send(entry).expect('Content-Type', /json/).end(assertCallback);
  };

  describe('PUT /entry for Happy Path With Required Data', function() {
    return it('responds with JSON success message', function(done) {
      var entry;

      entry = testData.fullyValidEntry();
      return put(entry, 200, function(err, res) {
        var message;

        should.not.exist(err);
        message = JSON.parse(res.text);
        should.exist(message);
        message.status.should.eql(200);
        message.message.should.eql('Successfully updated entry');
        return done();
      });
    });
  });

  describe('PUT /entry for each examples succeeds', function() {
    return it('responds with JSON success message', function(done) {
      var count, entry, file, files, _i, _len, _ref, _results;

      files = fs.readdirSync('./examples');
      count = files.length;
      _ref = fs.readdirSync('./examples');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        entry = JSON.parse(fs.readFileSync('./examples/' + file, 'utf8'));
        _results.push((function() {
          var doc;

          doc = entry;
          return put(doc, 200, function(err, res) {
            var message;

            count--;
            console.error('id: ' + doc.id);
            console.error(res.text);
            should.not.exist(err);
            message = JSON.parse(res.text);
            should.exist(message);
            message.status.should.eql(200);
            message.message.should.eql('Successfully updated entry');
            if (count === 0) {
              return done();
            }
          });
        })());
      }
      return _results;
    });
  });

  describe('PUT /entry for Failure Path With Invalid JSON', function() {
    return it('responds with JSON failure message', function(done) {
      var entry;

      entry = {
        "idNotAValidName": "FailurePathWithInvalidJSON"
      };
      return put(entry, 500, function(err, res) {
        var message;

        should.not.exist(err);
        message = JSON.parse(res.text);
        should.exist(message);
        message.status.should.eql(500);
        message.message.title.should.eql('Could not process your request due to validation errors');
        return done();
      });
    });
  });

}).call(this);
