// Generated by CoffeeScript 1.6.3
(function() {
  var app, checkLinkReturns200, config, fs, jp, req, request, requireCover, server, should, testData;

  requireCover = require('./requireCover')('app');

  fs = require('fs');

  request = require('supertest');

  server = requireCover('serverClass');

  should = require('should');

  testData = requireCover('testData');

  config = requireCover('config');

  jp = require('JSONPath')["eval"];

  req = require("request");

  app = server();

  checkLinkReturns200 = function(url, linkRequestComplete) {
    return req({
      uri: url,
      method: "GET"
    }, function(err, res, body) {
      if (err != null) {
        console.log('Error: ');
        console.dir(err);
      } else {
        if (res.statusCode === 200) {
          console.log("200 OK for: " + url);
        } else {
          console.log("" + res.statusCode + " NOT OK for: " + url);
        }
      }
      return linkRequestComplete();
    });
  };

  describe("Link checking", function() {
    return it('works well...', function(done) {
      this.timeout(180000);
      return req({
        uri: 'http://v1appcatalog.azurewebsites.net/entry',
        method: 'GET'
      }, function(err, res, body) {
        var count, data, errors, linkRequestComplete, path, url, urls, _i, _j, _len, _len1, _ref, _results;
        if (err != null) {
          console.log('Could not even get the App Catalog data!');
          return done();
        } else {
          data = JSON.parse(body);
          errors = [];
          urls = [];
          _ref = ['href', 'downloadUrl', 'moreInfoUrl', 'thumbhref'];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            path = _ref[_i];
            urls.push.apply(urls, jp(data, '$..' + path));
          }
          count = urls.length * 1;
          linkRequestComplete = function() {
            count--;
            console.log('Count: ' + count);
            if (count === 0) {
              console.log('Apparently done...' + count);
              return done();
            }
          };
          _results = [];
          for (_j = 0, _len1 = urls.length; _j < _len1; _j++) {
            url = urls[_j];
            _results.push(checkLinkReturns200(url, linkRequestComplete));
          }
          return _results;
        }
      });
    });
  });

  'it \'gets the list data and all links are valid\', (done) ->\ndescribe \'GET /entry returns all entries\', ->\n  it \'gets the list data and all links are valid\', (done) ->\n    req\n      uri: \'http://v1appcatalog.azurewebsites.net/entry\',\n      method: \'GET\'\n    , (err, res, body) ->\n      if err?\n        console.log \'Could not even get the App Catalog data!\'\n        done()\n      else\n        data = JSON.parse body\n        errors = []\n        urls = []\n        for path in [\'href\', \'downloadUrl\', \'moreInfoUrl\', \'thumbhref\']\n          urls.push jp(data, \'$..\' + path)...\n        \n        count = urls.length * 1\n        \n        linkRequestComplete = ->\n          count--\n          console.log \'Count: \' + count\n          if count == 0\n            console.log \'Apparently done...\' + count\n            done()\n\n        for url in urls \n          #checkSiteReturns404ForBadLink url, linkRequestComplete\n          checkLinkReturns200 url, linkRequestComplete';

}).call(this);
