// Generated by CoffeeScript 1.6.2
(function() {
  var MockAppCatalogEntry, must, requireCover, sarcastic, should, sinon, subject;

  requireCover = require('./requireCover')('app');

  sarcastic = requireCover('sarcastic');

  must = sarcastic.must;

  should = require('should');

  sinon = require('sinon');

  MockAppCatalogEntry = (function() {
    MockAppCatalogEntry.currentInstance = {};

    function MockAppCatalogEntry(body) {
      this.id = body.id;
      MockAppCatalogEntry.currentInstance = this;
    }

    MockAppCatalogEntry.prototype.save = sinon.spy();

    MockAppCatalogEntry.find = function() {};

    MockAppCatalogEntry.findOne = function() {};

    MockAppCatalogEntry.update = function() {};

    MockAppCatalogEntry.validate = function() {};

    return MockAppCatalogEntry;

  })();

  sarcastic.configTarget('./appCatalogEntry', MockAppCatalogEntry);

  subject = requireCover('service');

  describe('service', function() {
    describe('#findAll', function() {
      return must('call find', function() {
        sarcastic.getMock().expects('find').once().withArgs({}, '');
        return subject.findAll();
      });
    });
    describe('#findById', function() {
      return must('call findOne', function() {
        var id;

        id = 'v1clarityppm';
        sarcastic.getMock().expects('findOne').once().withArgs({
          id: id
        }, '');
        return subject.findById(id);
      });
    });
    return describe('#put', function() {
      return must('call validate and update', function() {
        var body, id, mock;

        id = 'v1clarityppm';
        body = {
          id: id
        };
        mock = sarcastic.getMock();
        sarcastic.getMock().expects('update').once().withArgs({
          id: id
        }, {
          $set: {
            id: id
          },
          $inc: {
            docVersion: 1
          }
        }, {
          upsert: true
        }).callsArg(3);
        sarcastic.getMock().expects('validate').once().withArgs(body).callsArg(1);
        return subject.put({
          id: id
        }, function(err) {});
      });
    });
  });

}).call(this);
