// Generated by CoffeeScript 1.7.1
(function() {
  var cors;

  cors = function(req, res, next) {
    var oneof;
    oneof = false;
    if (req.headers.origin) {
      res.header("Access-Control-Allow-Origin", req.headers.origin);
      oneof = true;
    }
    if (req.headers["access-control-request-method"]) {
      res.header("Access-Control-Allow-Methods", req.headers["access-control-request-method"]);
      oneof = true;
    }
    if (req.headers["access-control-request-headers"]) {
      res.header("Access-Control-Allow-Headers", req.headers["access-control-request-headers"]);
      oneof = true;
    }
    if (oneof) {
      res.header("Access-Control-Max-Age", 60 * 60 * 24 * 365);
    }
    if (oneof && req.method === "OPTIONS") {
      return res.send(200);
    } else {
      return next();
    }
  };

  module.exports.cors = cors;

}).call(this);
