// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(source) {
    var prop, _results;
    _results = [];
    for (prop in source) {
      _results.push(global[prop] = source[prop]);
    }
    return _results;
  };

}).call(this);
