// Generated by CoffeeScript 1.10.0
(function() {
  var data;

  data = {
    fullyValidEntry: function() {
      var entry;
      entry = {
        id: 'someIdHere',
        titleSection: this.titleSectionComplete(),
        descriptionSection: this.descriptionSectionComplete(),
        linksSection: this.linksSectionComplete(),
        updatesSection: this.updatesSectionComplete(),
        mediaSection: this.mediaSectionComplete()
      };
      return entry;
    },
    titleSectionMissing: function() {
      var entry;
      entry = this.fullyValidEntry();
      delete entry.titleSection;
      return entry;
    },
    titleSectionEmpty: function() {
      var entry;
      entry = this.fullyValidEntry();
      entry.titleSection = {};
      return entry;
    },
    titleSectionComplete: function() {
      return {
        name: 'String Name',
        shortDescription: 'Free short description',
        pricing: 'Free',
        support: {
          text: 'Text label',
          href: 'http://somesite.com'
        }
      };
    },
    descriptionSectionMissing: function() {
      var entry;
      entry = this.fullyValidEntry();
      delete entry.descriptionSection;
      return entry;
    },
    descriptionSectionEmpty: function() {
      var entry;
      entry = this.fullyValidEntry();
      entry.descriptionSection = {};
      return entry;
    },
    descriptionSectionComplete: function() {
      return {
        description: 'This is a valid description for an entry'
      };
    },
    linksSectionMissing: function() {
      var entry;
      entry = this.fullyValidEntry();
      delete entry.linksSection;
      return entry;
    },
    linksSectionEmpty: function() {
      var entry;
      entry = this.fullyValidEntry();
      entry.linksSection = {};
      return entry;
    },
    linksSectionComplete: function() {
      return [
        {
          "type": "download",
          "href": "http://platform.versionone.com.s3.amazonaws.com/downloads/v1clarityppm_0.3.2.13.zip",
          "title": "Download Latest Stable Release"
        }, {
          "type": "download",
          "href": "http://platform.versionone.com.s3.amazonaws.com/downloads/v1clarityppm_0.3.2.13.zip",
          "title": "Download Latest Nightly Build"
        }, {
          "type": "code",
          "href": "https://github.com/versionone/V1ClarityPPM",
          "title": "Source Code"
        }, {
          "type": "documentation",
          "href": "https://github.com/versionone/V1ClarityPPM/blob/master/README.md",
          "title": "Documentation"
        }, {
          "type": "license",
          "href": "https://github.com/versionone/V1ClarityPPM/blob/master/LICENSE.md",
          "title": "Modified BSD (3-clause) License"
        }, {
          "type": "foo",
          "href": "https://github.com/versionone/V1ClarityPPM/blob/master",
          "title": "Sample configuration"
        }
      ];
    },
    updatesSectionMissing: function() {
      var entry;
      entry = this.fullyValidEntry();
      delete entry.updatesSection;
      return entry;
    },
    updatesSectionEmpty: function() {
      var entry;
      entry = this.fullyValidEntry();
      entry.updatesSection = {};
      return entry;
    },
    updatesSectionWithEmptyUpdates: function() {
      var entry;
      entry = this.fullyValidEntry();
      entry.updatesSection.updates = [{}];
      return entry;
    },
    updatesSectionComplete: function() {
      var obj;
      obj = {
        updates: [
          {
            date: "2013-02-14T17:45:00Z",
            description: "stabilizing timesheet workflow",
            version: "0.3.2.13",
            releaseNotes: "Florum gypsum dimsum",
            moreInfoUrl: "http://example.com",
            qualityBand: "mature",
            downloadUrl: "http://platform.versionone.com.s3.amazonaws.com/downloads/v1clarityppm_0.3.2.13.zip"
          }, {
            date: "2013-02-14T17:45:00Z",
            description: "better timesheet support",
            version: "0.3.3.5",
            releaseNotes: "Florum gypsum dimsum",
            moreInfoUrl: "http://more.exampleForYou.com",
            qualityBand: "sapling",
            downloadUrl: "http://platform.versionone.com.s3.amazonaws.com/downloads/v1clarityppm_0.2.1.10.zip"
          }
        ],
        qualityBands: {
          sapling: {
            shortDescription: "The product is undergoing rapid growth. The code works but expect major changes.",
            href: "https://github.com/versionone/V1ClarityPPM/blob/master/CONTRIBUTING.md#sapling"
          },
          mature: {
            shortDescription: "The product is stable. The code will continue to evolve with minimum breaking changes.",
            href: "https://github.com/versionone/V1ClarityPPM/blob/master/CONTRIBUTING.md#mature"
          }
        }
      };
      return obj;
    },
    mediaSectionComplete: function() {
      return [
        {
          "title": "Home",
          "caption": "The home image",
          "mimetype": "image/png",
          "href": "http://absolute.content.com/gallery/Projekt_es_Projekt_portfolio_menedzsment_ca_clarity_ppm_masolata.jpg",
          "thumbhref": "https://absolute.content.com/gallery/Projekt_es_Projekt_portfolio_menedzsment_ca_clarity_ppm_masolata.jpg"
        }
      ];
    }
  };

  module.exports = data;

}).call(this);
