// Generated by CoffeeScript 1.6.2
(function() {
  define(["backbone-min", "catalogApp"], function(Backbone, catalogApp) {
    catalogApp.EntryDetailsView = Backbone.View.extend({
      initialize: function() {
        return this.model.bind("change", this.render, this);
      },
      render: function() {
        var entry, getPopContent, getPopTitle, html, view;

        getPopTitle = function(target) {
          var selector, title;

          selector = "#qualityBand" + target + "_title";
          title = view.find(selector).html();
          return title;
        };
        getPopContent = function(target) {
          var content, selector;

          selector = "#qualityBand" + target + "_content";
          content = view.find(selector).html();
          return content;
        };
        entry = this.model.toJSON();
        view = $(this.el);
        html = this.template(entry);
        view.html(html);
        view.find(".details").html(new catalogApp.EntryDetailsInfoView({
          model: entry
        }).render().el);
        view.find(".updates").html(new catalogApp.EntryUpdatesView({
          model: this.model.get("updates")
        }).render().el);
        view.find(".qualityBandPopover").each(function() {
          var content, popOver, qualityBand, title;

          popOver = $(this);
          qualityBand = popOver.attr("data-qualityBand");
          title = getPopTitle(qualityBand);
          content = getPopContent(qualityBand);
          return popOver.popover({
            title: title,
            content: content,
            html: true,
            animation: true
          });
        });
        return this;
      }
    });
    catalogApp.EntryDetailsInfoView = Backbone.View.extend({
      render: function() {
        var entry;

        entry = this.model;
        $(this.el).html(this.template(entry));
        return this;
      }
    });
    return catalogApp.EntryUpdatesView = Backbone.View.extend({
      render: function() {
        var updates;

        updates = this.model;
        $(this.el).html(this.template(updates));
        return this;
      }
    });
  });

}).call(this);
