// Generated by CoffeeScript 1.6.2
(function() {
  define(["backbone-min", "catalogApp", "handlebars"], function(Backbone, catalogApp, Handlebars) {
    Handlebars.registerHelper('callToAction', function(context, block) {
      var callToAction;

      callToAction = context.textLinks[0];
      return catalogApp.renderTemplateSafeString('CallToActionView', callToAction);
    });
    return catalogApp.EntryDetailsView = Backbone.View.extend({
      initialize: function() {
        return this.model.bind('change', this.render, this);
      },
      render: function() {
        var entry, getPopContent, getPopTitle, html, view;

        getPopTitle = function(target) {
          var selector, title;

          selector = "#qualityBand" + target + "_title";
          title = view.find(selector).html();
          return title;
        };
        getPopContent = function(target) {
          var content, selector;

          selector = "#qualityBand" + target + "_content";
          content = view.find(selector).html();
          return content;
        };
        entry = this.model.toJSON();
        view = $(this.el);
        html = this.template(entry);
        view.html(html);
        view.find('.entryTitle').html(catalogApp.renderView('TitleView', entry));
        view.find('.qualifiers').html(catalogApp.renderView('QualifiersView', entry));
        view.find('.media').html(catalogApp.renderView('MediaView', this.model.get('visualLinks')));
        view.find('.details').html(catalogApp.renderView('EntryDetailsInfoView', entry));
        view.find('.updates').html(catalogApp.renderView('EntryUpdatesView', this.model.get('updates')));
        view.find(".qualityBandPopover").each(function() {
          var content, popOver, qualityBand, title;

          popOver = $(this);
          qualityBand = popOver.attr("data-qualityBand");
          title = getPopTitle(qualityBand);
          content = getPopContent(qualityBand);
          return popOver.popover({
            title: title,
            content: content,
            html: true,
            animation: true
          });
        });
        return this;
      }
    });
  });

}).call(this);
